<footer>
        CSC 174: Advanced Front-end Web Design and Development
    </footer>

    <nav>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="extra-curriculars.php">Extra Curriculars</a></li>
            <li><a href="courses.php">Courses</a></li>
            <li><a href="future-plans.php">Future Plans</a></li>
        </ul>
    </nav>

<script src="https://code.jquery.com/jquery.js"></script>
<script src="js/menu-highlighter.js"></script>
</body>


</html>