<link rel="stylesheet" href="css/styles.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300i,700%7CStaatliches" rel="stylesheet">
	
</head>

<body class="container">

    <header>
        <a href="index.php">
            <h1>Giovanni Ilacqua</h1>
            <img class="profile-picture" src="images/profile_photo.jpg" alt="A profile photo">
        </a>
    </header>

    <aside>
        <ul>
            <li>Computer Science Major</li>
            <li>Qualified Fitness Instructor</li>
            <li>Graphic Designer</li>
        </ul>
    </aside>




    